services:
  - type: web
    name: visiocr-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn visiOcr.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: visiOcr.settings
      - key: PYTHON_VERSION
        value: 3.10.7
    plan: free
